security:
  oauth2:
    authorization:
      endpoint: http://localhost:8080/oauth/authorize
    client:
      client-id: auth-server
      client-secret: auth-server-secret
jwt:
  signing-key: jwt-sample-key

spring:
  security:
    oauth2:
      client:
        clientId: auth-server
        clientSecret: auth-server-secret
        accessTokenUri: http://localhost:8080/oauth/token
      resource:
        jwt:
          key-value: |
            jwt-sample-key